export const contacts = [
    { profilePicture: "https://randomuser.me/api/portraits/men/1.jpg", name: "John Doe", time: "10:30 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/2.jpg", name: "Jane Smith", time: "11:15 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/3.jpg", name: "Robert Johnson", time: "9:45 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/4.jpg", name: "Emily Davis", time: "12:20 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/5.jpg", name: "Michael Brown", time: "2:05 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/6.jpg", name: "Linda White", time: "1:30 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/7.jpg", name: "David Clark", time: "3:40 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/8.jpg", name: "Sarah Lewis", time: "4:10 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/9.jpg", name: "James Walker", time: "5:50 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/10.jpg", name: "Patricia Hall", time: "6:30 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/11.jpg", name: "Christopher Allen", time: "7:15 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/12.jpg", name: "Jessica Young", time: "8:45 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/13.jpg", name: "Daniel Hernandez", time: "9:20 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/14.jpg", name: "Karen King", time: "10:00 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/15.jpg", name: "Matthew Wright", time: "10:45 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/16.jpg", name: "Nancy Lopez", time: "11:30 PM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/17.jpg", name: "Joshua Scott", time: "12:15 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/18.jpg", name: "Betty Green", time: "1:00 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/19.jpg", name: "Andrew Adams", time: "1:45 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/20.jpg", name: "Dorothy Hill", time: "2:30 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/21.jpg", name: "Joseph Baker", time: "3:15 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/22.jpg", name: "Sandra Turner", time: "4:00 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/23.jpg", name: "Charles Carter", time: "4:45 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/24.jpg", name: "Shirley Mitchell", time: "5:30 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/25.jpg", name: "Brian Perez", time: "6:15 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/26.jpg", name: "Ruth Roberts", time: "7:00 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/27.jpg", name: "Kevin Nelson", time: "7:45 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/28.jpg", name: "Maria Moore", time: "8:30 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/men/29.jpg", name: "George Thompson", time: "9:15 AM" },
    { profilePicture: "https://randomuser.me/api/portraits/women/30.jpg", name: "Barbara Anderson", time: "10:00 AM" }
  ];
  